

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Models;
using MyProject.Models;

namespace DataAccess.Db
{
    public class ApplicationDbContext : IdentityDbContext<IdentityUser>
    {
        
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductImage> ProductImages { get; set; }
        public DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public DbSet<Review> Reviews { get; set; }
        public DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public DbSet<OrderHeader> OrderHeaders { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            
            
            modelBuilder.Entity<Category>().HasData(
                new Category { Id = 1, Name = "Men Clothing" },
                new Category { Id = 2, Name = "Women Clothing" },
                new Category { Id = 3, Name = "Kids Clothing" },
                new Category { Id = 4, Name = "Men Shoes" },
                new Category { Id = 5, Name = "Women Shoes" },
                new Category { Id = 6, Name = "Kids Shoes" },
                new Category { Id = 7, Name = "Bags" },
                new Category { Id = 8, Name = "Backpacks" },
                new Category { Id = 9, Name = "Men Accessories" },
                new Category { Id = 10, Name = "Women Accessories" },
                new Category { Id = 11, Name = "Watches" },
                new Category { Id = 12, Name = "Sunglasses" },
                new Category { Id = 13, Name = "Men Perfumes" },
                new Category { Id = 14, Name = "Women Perfumes" },
                new Category { Id = 15, Name = "Cosmetics" },
                new Category { Id = 16, Name = "Makeup" },
                new Category { Id = 17, Name = "Skincare" },
                new Category { Id = 18, Name = "Hair Care" },
                new Category { Id = 19, Name = "Personal Care" },
                new Category { Id = 20, Name = "Health & Beauty" },
                new Category { Id = 21, Name = "Mobiles" },
                new Category { Id = 22, Name = "Tablets" },
                new Category { Id = 23, Name = "Laptops" },
                new Category { Id = 24, Name = "Computers" },
                new Category { Id = 25, Name = "Smart Watches" },
                new Category { Id = 26, Name = "Headphones" },
                new Category { Id = 27, Name = "Speakers" },
                new Category { Id = 28, Name = "Cameras" },
                new Category { Id = 29, Name = "Gaming Consoles" },
                new Category { Id = 30, Name = "Video Games" },
                new Category { Id = 31, Name = "TV & Audio" },
                new Category { Id = 32, Name = "Home Appliances" },
                new Category { Id = 33, Name = "Kitchen Appliances" },
                new Category { Id = 34, Name = "Refrigerators" },
                new Category { Id = 35, Name = "Washing Machines" },
                new Category { Id = 36, Name = "Cookers" },
                new Category { Id = 37, Name = "Microwaves" },
                new Category { Id = 38, Name = "Vacuum Cleaners" },
                new Category { Id = 39, Name = "Furniture" },
                new Category { Id = 40, Name = "Living Room" },
                new Category { Id = 41, Name = "Bedroom" },
                new Category { Id = 42, Name = "Dining Room" },
                new Category { Id = 43, Name = "Office Furniture" },
                new Category { Id = 44, Name = "Garden Furniture" },
                new Category { Id = 45, Name = "Home Decor" },
                new Category { Id = 46, Name = "Lighting" },
                new Category { Id = 47, Name = "Bedding" },
                new Category { Id = 48, Name = "Carpets" },
                new Category { Id = 49, Name = "Kitchenware" },
                new Category { Id = 50, Name = "Tableware" },
                new Category { Id = 51, Name = "Cookware" },
                new Category { Id = 52, Name = "Bakeware" },
                new Category { Id = 53, Name = "Storage & Organization" },
                new Category { Id = 54, Name = "Cleaning Supplies" },
                new Category { Id = 55, Name = "Groceries" },
                new Category { Id = 56, Name = "Snacks" },
                new Category { Id = 57, Name = "Beverages" },
                new Category { Id = 58, Name = "Breakfast Items" },
                new Category { Id = 59, Name = "Canned Food" },
                new Category { Id = 60, Name = "Fresh Fruits" },
                new Category { Id = 61, Name = "Fresh Vegetables" },
                new Category { Id = 62, Name = "Dairy Products" },
                new Category { Id = 63, Name = "Meat & Poultry" },
                new Category { Id = 64, Name = "Seafood" },
                new Category { Id = 65, Name = "Frozen Food" },
                new Category { Id = 66, Name = "Baby Products" },
                new Category { Id = 67, Name = "Diapers" },
                new Category { Id = 68, Name = "Baby Care" },
                new Category { Id = 69, Name = "Toys" },
                new Category { Id = 70, Name = "Board Games" },
                new Category { Id = 71, Name = "Outdoor Games" },
                new Category { Id = 72, Name = "Books" },
                new Category { Id = 73, Name = "Novels" },
                new Category { Id = 74, Name = "School Supplies" },
                new Category { Id = 75, Name = "Office Supplies" },
                new Category { Id = 76, Name = "Art Supplies" },
                new Category { Id = 77, Name = "Sports Equipment" },
                new Category { Id = 78, Name = "Fitness Equipment" },
                new Category { Id = 79, Name = "Camping Gear" },
                new Category { Id = 80, Name = "Travel Accessories" },
                new Category { Id = 81, Name = "Car Accessories" },
                new Category { Id = 82, Name = "Car Electronics" },
                new Category { Id = 83, Name = "Motorcycle Gear" },
                new Category { Id = 84, Name = "Pet Supplies" },
                new Category { Id = 85, Name = "Pet Food" },
                new Category { Id = 86, Name = "Pet Toys" },
                new Category { Id = 87, Name = "Garden Tools" },
                new Category { Id = 88, Name = "Plants & Seeds" },
                new Category { Id = 89, Name = "DIY Tools" },
                new Category { Id = 90, Name = "Hand Tools" },
                new Category { Id = 91, Name = "Power Tools" },
                new Category { Id = 92, Name = "Building Materials" },
                new Category { Id = 93, Name = "Electrical Supplies" },
                new Category { Id = 94, Name = "Plumbing Supplies" },
                new Category { Id = 95, Name = "Safety Equipment" },
                new Category { Id = 96, Name = "Travel Luggage" },
                new Category { Id = 97, Name = "Jewelry" },
                new Category { Id = 98, Name = "Gold & Silver" },
                new Category { Id = 99, Name = "Collectibles" },
                new Category { Id = 100, Name = "Gifts" }
            );

            modelBuilder.Entity<Product>().HasData(
                new Product { Id = 1, Title = "Nike Air Max Shoes", Description = "Comfortable running shoes with modern design", Quantity = 120, Brand = "Nike", ListPrice = 150, Price = 140, Price50 = 130, Price100 = 120, CategoryId = 4 },
                new Product { Id = 2, Title = "Samsung Galaxy S23", Description = "Latest flagship smartphone with high performance camera", Quantity = 60, Brand = "Samsung", ListPrice = 900, Price = 850, Price50 = 820, Price100 = 790, CategoryId = 21 },
                new Product { Id = 3, Title = "Adidas Backpack", Description = "Durable backpack for travel and school", Quantity = 200, Brand = "Adidas", ListPrice = 70, Price = 65, Price50 = 60, Price100 = 55, CategoryId = 8 },
                new Product { Id = 4, Title = "Apple MacBook Pro 14", Description = "Powerful laptop with M2 chip for professionals", Quantity = 35, Brand = "Apple", ListPrice = 2000, Price = 1900, Price50 = 1850, Price100 = 1800, CategoryId = 23 },
                new Product { Id = 5, Title = "Gucci Handbag", Description = "Luxury leather handbag for women", Quantity = 50, Brand = "Gucci", ListPrice = 1200, Price = 1100, Price50 = 1050, Price100 = 1000, CategoryId = 7 },
                new Product { Id = 6, Title = "Sony WH-1000XM5 Headphones", Description = "Noise cancelling wireless headphones", Quantity = 80, Brand = "Sony", ListPrice = 400, Price = 380, Price50 = 360, Price100 = 340, CategoryId = 26 },
                new Product { Id = 7, Title = "LG 55 Inch Smart TV", Description = "4K Ultra HD Smart LED TV", Quantity = 40, Brand = "LG", ListPrice = 750, Price = 720, Price50 = 700, Price100 = 680, CategoryId = 31 },
                new Product { Id = 8, Title = "Dell XPS 13 Laptop", Description = "Slim and powerful laptop for work", Quantity = 25, Brand = "Dell", ListPrice = 1500, Price = 1450, Price50 = 1400, Price100 = 1350, CategoryId = 23 },
                new Product { Id = 9, Title = "Nestle Chocolate Pack", Description = "Delicious assorted chocolate pack", Quantity = 300, Brand = "Nestle", ListPrice = 15, Price = 14, Price50 = 13, Price100 = 12, CategoryId = 56 },
                new Product { Id = 10, Title = "Levi’s Jeans", Description = "Classic denim jeans for men", Quantity = 180, Brand = "Levi’s", ListPrice = 60, Price = 55, Price50 = 52, Price100 = 50, CategoryId = 1 },
                new Product { Id = 11, Title = "HP Laser Printer", Description = "High speed wireless laser printer", Quantity = 50, Brand = "HP", ListPrice = 250, Price = 240, Price50 = 230, Price100 = 220, CategoryId = 75 },
                new Product { Id = 12, Title = "Adidas Running T-Shirt", Description = "Lightweight sportswear t-shirt", Quantity = 150, Brand = "Adidas", ListPrice = 35, Price = 32, Price50 = 30, Price100 = 28, CategoryId = 1 },
                new Product { Id = 13, Title = "Apple iPad Air", Description = "Light and powerful tablet with Retina display", Quantity = 60, Brand = "Apple", ListPrice = 650, Price = 630, Price50 = 610, Price100 = 590, CategoryId = 22 },
                new Product { Id = 14, Title = "Rolex Submariner Watch", Description = "Luxury Swiss made men’s watch", Quantity = 15, Brand = "Rolex", ListPrice = 9000, Price = 8800, Price50 = 8700, Price100 = 8600, CategoryId = 11 },
                new Product { Id = 15, Title = "Canon EOS 90D Camera", Description = "Professional DSLR camera for photography", Quantity = 20, Brand = "Canon", ListPrice = 1200, Price = 1150, Price50 = 1100, Price100 = 1050, CategoryId = 28 },
                new Product { Id = 16, Title = "Sony PlayStation 5", Description = "Latest generation gaming console", Quantity = 40, Brand = "Sony", ListPrice = 600, Price = 580, Price50 = 560, Price100 = 540, CategoryId = 29 },
                new Product { Id = 17, Title = "Microsoft Xbox Series X", Description = "Powerful gaming console with 4K support", Quantity = 35, Brand = "Microsoft", ListPrice = 550, Price = 530, Price50 = 510, Price100 = 490, CategoryId = 29 },
                new Product { Id = 18, Title = "Puma Sports Shoes", Description = "Comfortable shoes for everyday wear", Quantity = 110, Brand = "Puma", ListPrice = 100, Price = 95, Price50 = 90, Price100 = 85, CategoryId = 4 },
                new Product { Id = 19, Title = "Samsung Galaxy Watch", Description = "Smartwatch with health tracking", Quantity = 75, Brand = "Samsung", ListPrice = 350, Price = 340, Price50 = 330, Price100 = 320, CategoryId = 25 },
                new Product { Id = 20, Title = "KitchenAid Mixer", Description = "Professional stand mixer for baking", Quantity = 45, Brand = "KitchenAid", ListPrice = 400, Price = 380, Price50 = 370, Price100 = 360, CategoryId = 33 },
                new Product { Id = 21, Title = "Nike Sports Cap", Description = "Adjustable unisex sports cap", Quantity = 160, Brand = "Nike", ListPrice = 25, Price = 23, Price50 = 22, Price100 = 20, CategoryId = 9 },
                new Product { Id = 22, Title = "Apple AirPods Pro", Description = "Noise cancelling wireless earbuds", Quantity = 90, Brand = "Apple", ListPrice = 250, Price = 240, Price50 = 230, Price100 = 220, CategoryId = 26 },
                new Product { Id = 23, Title = "Philips Blender", Description = "High speed electric blender", Quantity = 70, Brand = "Philips", ListPrice = 80, Price = 75, Price50 = 72, Price100 = 70, CategoryId = 33 },
                new Product { Id = 24, Title = "Gucci Sunglasses", Description = "Luxury designer sunglasses", Quantity = 55, Brand = "Gucci", ListPrice = 500, Price = 480, Price50 = 470, Price100 = 460, CategoryId = 12 },
                new Product { Id = 25, Title = "Samsung 1TB SSD", Description = "High speed solid state drive", Quantity = 100, Brand = "Samsung", ListPrice = 150, Price = 145, Price50 = 140, Price100 = 135, CategoryId = 23 },
                new Product { Id = 26, Title = "Bosch Power Drill", Description = "Cordless electric drill with battery", Quantity = 80, Brand = "Bosch", ListPrice = 200, Price = 190, Price50 = 185, Price100 = 180, CategoryId = 91 },
                new Product { Id = 27, Title = "Nestle Coffee Pack", Description = "Premium instant coffee blend", Quantity = 250, Brand = "Nestle", ListPrice = 12, Price = 11, Price50 = 10, Price100 = 9, CategoryId = 57 },
                new Product { Id = 28, Title = "Nike Training Shorts", Description = "Breathable sports shorts", Quantity = 140, Brand = "Nike", ListPrice = 40, Price = 38, Price50 = 36, Price100 = 34, CategoryId = 1 },
                new Product { Id = 29, Title = "Samsung 32 Inch Monitor", Description = "Curved gaming monitor", Quantity = 60, Brand = "Samsung", ListPrice = 300, Price = 290, Price50 = 280, Price100 = 270, CategoryId = 23 },
                new Product { Id = 30, Title = "Adidas Hoodie", Description = "Warm hoodie for winter", Quantity = 130, Brand = "Adidas", ListPrice = 65, Price = 60, Price50 = 58, Price100 = 55, CategoryId = 1 },
                new Product { Id = 31, Title = "Apple Watch Ultra", Description = "Advanced smartwatch with GPS", Quantity = 40, Brand = "Apple", ListPrice = 800, Price = 780, Price50 = 760, Price100 = 740, CategoryId = 25 },
                new Product { Id = 32, Title = "Sony 4K Camcorder", Description = "Professional 4K video camera", Quantity = 25, Brand = "Sony", ListPrice = 1800, Price = 1750, Price50 = 1720, Price100 = 1700, CategoryId = 28 },
                new Product { Id = 33, Title = "Levi’s Jacket", Description = "Denim jacket for men", Quantity = 95, Brand = "Levi’s", ListPrice = 85, Price = 80, Price50 = 78, Price100 = 75, CategoryId = 1 },
                new Product { Id = 34, Title = "Samsung Microwave", Description = "Compact digital microwave", Quantity = 70, Brand = "Samsung", ListPrice = 130, Price = 125, Price50 = 120, Price100 = 115, CategoryId = 37 },
                new Product { Id = 35, Title = "Nike Running Socks", Description = "Breathable cotton socks", Quantity = 200, Brand = "Nike", ListPrice = 15, Price = 14, Price50 = 13, Price100 = 12, CategoryId = 9 },
                new Product { Id = 36, Title = "Asus Gaming Laptop", Description = "High performance laptop for gamers", Quantity = 30, Brand = "Asus", ListPrice = 1700, Price = 1650, Price50 = 1620, Price100 = 1600, CategoryId = 23 },
                new Product { Id = 37, Title = "Sony Bluetooth Speaker", Description = "Portable wireless speaker", Quantity = 100, Brand = "Sony", ListPrice = 120, Price = 115, Price50 = 110, Price100 = 105, CategoryId = 27 },
                new Product { Id = 38, Title = "Gucci Wallet", Description = "Luxury leather wallet", Quantity = 40, Brand = "Gucci", ListPrice = 400, Price = 380, Price50 = 370, Price100 = 360, CategoryId = 10 },
                new Product { Id = 39, Title = "Apple iPhone 14 Pro", Description = "Latest iPhone with A16 chip", Quantity = 55, Brand = "Apple", ListPrice = 1200, Price = 1150, Price50 = 1120, Price100 = 1100, CategoryId = 21 },
                new Product { Id = 40, Title = "Nike Gym Bag", Description = "Durable sports duffel bag", Quantity = 85, Brand = "Nike", ListPrice = 70, Price = 65, Price50 = 62, Price100 = 60, CategoryId = 7 },
                new Product { Id = 41, Title = "Samsung Soundbar", Description = "High quality wireless soundbar", Quantity = 45, Brand = "Samsung", ListPrice = 250, Price = 240, Price50 = 230, Price100 = 220, CategoryId = 27 },
                new Product { Id = 42, Title = "Rolex Oyster Watch", Description = "Luxury classic men’s watch", Quantity = 10, Brand = "Rolex", ListPrice = 10000, Price = 9800, Price50 = 9700, Price100 = 9600, CategoryId = 11 },
                new Product { Id = 43, Title = "Sony PS5 Controller", Description = "Wireless DualSense controller", Quantity = 150, Brand = "Sony", ListPrice = 70, Price = 65, Price50 = 62, Price100 = 60, CategoryId = 30 },
                new Product { Id = 44, Title = "Apple iMac 24 Inch", Description = "All-in-one desktop computer", Quantity = 20, Brand = "Apple", ListPrice = 1600, Price = 1550, Price50 = 1520, Price100 = 1500, CategoryId = 24 },
                new Product { Id = 45, Title = "Nike Basketball", Description = "Durable outdoor basketball", Quantity = 140, Brand = "Nike", ListPrice = 40, Price = 38, Price50 = 36, Price100 = 34, CategoryId = 77 },
                new Product { Id = 46, Title = "Samsung Galaxy Tab S8", Description = "Powerful Android tablet", Quantity = 45, Brand = "Samsung", ListPrice = 700, Price = 680, Price50 = 660, Price100 = 640, CategoryId = 22 },
                new Product { Id = 47, Title = "Levi’s T-Shirt", Description = "Cotton t-shirt for men", Quantity = 180, Brand = "Levi’s", ListPrice = 30, Price = 28, Price50 = 27, Price100 = 25, CategoryId = 1 },
                new Product { Id = 48, Title = "Gucci Belt", Description = "Designer leather belt", Quantity = 50, Brand = "Gucci", ListPrice = 350, Price = 340, Price50 = 330, Price100 = 320, CategoryId = 10 },
                new Product { Id = 49, Title = "Sony Bravia 65 Inch TV", Description = "4K HDR Smart TV", Quantity = 30, Brand = "Sony", ListPrice = 1200, Price = 1150, Price50 = 1120, Price100 = 1100, CategoryId = 31 },
                new Product { Id = 50, Title = "Nike Training Gloves", Description = "Fitness training gloves", Quantity = 100, Brand = "Nike", ListPrice = 25, Price = 23, Price50 = 22, Price100 = 20, CategoryId = 77 }
            );
            modelBuilder.Entity<Product>().HasData(
                new Product { Id = 51, Title = "Adidas Sports Jacket", Description = "Lightweight sports jacket for outdoor activities", Quantity = 95, Brand = "Adidas", ListPrice = 90, Price = 85, Price50 = 80, Price100 = 75, CategoryId = 1 },
                new Product { Id = 52, Title = "Apple iPhone Charger", Description = "Fast charging adapter for iPhone", Quantity = 200, Brand = "Apple", ListPrice = 30, Price = 28, Price50 = 27, Price100 = 25, CategoryId = 21 },
                new Product { Id = 53, Title = "Samsung Portable SSD 2TB", Description = "High-speed external storage drive", Quantity = 70, Brand = "Samsung", ListPrice = 250, Price = 240, Price50 = 230, Price100 = 220, CategoryId = 23 },
                new Product { Id = 54, Title = "Nike Dri-FIT Pants", Description = "Comfortable training pants", Quantity = 120, Brand = "Nike", ListPrice = 60, Price = 55, Price50 = 52, Price100 = 50, CategoryId = 1 },
                new Product { Id = 55, Title = "Sony PlayStation Plus Card", Description = "12 months subscription card", Quantity = 300, Brand = "Sony", ListPrice = 60, Price = 55, Price50 = 53, Price100 = 50, CategoryId = 29 },
                new Product { Id = 56, Title = "Gucci Perfume", Description = "Luxury fragrance for women", Quantity = 70, Brand = "Gucci", ListPrice = 150, Price = 140, Price50 = 135, Price100 = 130, CategoryId = 14 },
                new Product { Id = 57, Title = "Logitech Wireless Mouse", Description = "Ergonomic design wireless mouse", Quantity = 180, Brand = "Logitech", ListPrice = 40, Price = 38, Price50 = 36, Price100 = 34, CategoryId = 23 },
                new Product { Id = 58, Title = "Apple iPad Keyboard", Description = "Magic keyboard for iPad Pro", Quantity = 40, Brand = "Apple", ListPrice = 300, Price = 290, Price50 = 280, Price100 = 270, CategoryId = 22 },
                new Product { Id = 59, Title = "Nike Training Bag", Description = "Sports duffel bag for gym use", Quantity = 95, Brand = "Nike", ListPrice = 75, Price = 70, Price50 = 68, Price100 = 65, CategoryId = 7 },
                new Product { Id = 60, Title = "Samsung Galaxy Buds 2", Description = "Wireless earbuds with ANC", Quantity = 85, Brand = "Samsung", ListPrice = 160, Price = 150, Price50 = 145, Price100 = 140, CategoryId = 26 },
                new Product { Id = 61, Title = "Adidas Kids Shoes", Description = "Comfortable sneakers for kids", Quantity = 140, Brand = "Adidas", ListPrice = 50, Price = 48, Price50 = 46, Price100 = 44, CategoryId = 6 },
                new Product { Id = 62, Title = "Sony PS5 Game - Spider Man", Description = "Exclusive PS5 action game", Quantity = 100, Brand = "Sony", ListPrice = 70, Price = 65, Price50 = 62, Price100 = 60, CategoryId = 30 },
                new Product { Id = 63, Title = "Canon Printer Ink", Description = "High-quality black ink cartridge", Quantity = 150, Brand = "Canon", ListPrice = 25, Price = 23, Price50 = 22, Price100 = 20, CategoryId = 75 },
                new Product { Id = 64, Title = "LG Refrigerator 400L", Description = "Large double-door refrigerator", Quantity = 20, Brand = "LG", ListPrice = 1100, Price = 1080, Price50 = 1060, Price100 = 1040, CategoryId = 34 },
                new Product { Id = 65, Title = "Nike Running Cap", Description = "Breathable lightweight cap", Quantity = 90, Brand = "Nike", ListPrice = 22, Price = 20, Price50 = 19, Price100 = 18, CategoryId = 9 },
                new Product { Id = 66, Title = "Apple Magic Mouse", Description = "Wireless mouse with multi-touch", Quantity = 70, Brand = "Apple", ListPrice = 100, Price = 95, Price50 = 92, Price100 = 90, CategoryId = 23 },
                new Product { Id = 67, Title = "Samsung Washing Machine", Description = "Front load washing machine", Quantity = 25, Brand = "Samsung", ListPrice = 900, Price = 880, Price50 = 860, Price100 = 850, CategoryId = 35 },
                new Product { Id = 68, Title = "Nike Kids T-Shirt", Description = "Cotton t-shirt for kids", Quantity = 130, Brand = "Nike", ListPrice = 20, Price = 18, Price50 = 17, Price100 = 16, CategoryId = 3 },
                new Product { Id = 69, Title = "Sony 55 Inch OLED TV", Description = "4K Ultra HD Smart OLED TV", Quantity = 35, Brand = "Sony", ListPrice = 1300, Price = 1270, Price50 = 1250, Price100 = 1230, CategoryId = 31 },
                new Product { Id = 70, Title = "Gucci Leather Shoes", Description = "Luxury men’s leather shoes", Quantity = 45, Brand = "Gucci", ListPrice = 900, Price = 880, Price50 = 860, Price100 = 840, CategoryId = 4 },
                new Product { Id = 71, Title = "Philips Air Fryer", Description = "Healthy cooking air fryer", Quantity = 65, Brand = "Philips", ListPrice = 250, Price = 240, Price50 = 230, Price100 = 220, CategoryId = 33 },
                new Product { Id = 72, Title = "Adidas Hoodie Kids", Description = "Winter hoodie for children", Quantity = 95, Brand = "Adidas", ListPrice = 45, Price = 42, Price50 = 40, Price100 = 38, CategoryId = 3 },
                new Product { Id = 73, Title = "Apple MacBook Air", Description = "Lightweight laptop with M1 chip", Quantity = 50, Brand = "Apple", ListPrice = 1000, Price = 950, Price50 = 920, Price100 = 900, CategoryId = 23 },
                new Product { Id = 74, Title = "Samsung Curved Monitor", Description = "34 inch ultrawide curved monitor", Quantity = 30, Brand = "Samsung", ListPrice = 650, Price = 630, Price50 = 610, Price100 = 590, CategoryId = 23 },
                new Product { Id = 75, Title = "Nike Training Shoes Women", Description = "Comfortable training shoes for women", Quantity = 100, Brand = "Nike", ListPrice = 80, Price = 75, Price50 = 72, Price100 = 70, CategoryId = 5 },
                new Product { Id = 76, Title = "Sony Wireless Earbuds", Description = "Compact noise cancelling earbuds", Quantity = 85, Brand = "Sony", ListPrice = 200, Price = 190, Price50 = 185, Price100 = 180, CategoryId = 26 },
                new Product { Id = 77, Title = "Gucci Scarf", Description = "Luxury designer scarf", Quantity = 60, Brand = "Gucci", ListPrice = 400, Price = 380, Price50 = 370, Price100 = 360, CategoryId = 10 },
                new Product { Id = 78, Title = "Samsung Galaxy Z Fold", Description = "Innovative foldable smartphone", Quantity = 25, Brand = "Samsung", ListPrice = 1800, Price = 1750, Price50 = 1720, Price100 = 1700, CategoryId = 21 },
                new Product { Id = 79, Title = "Nike Sports Socks", Description = "Breathable cotton socks pack", Quantity = 220, Brand = "Nike", ListPrice = 15, Price = 14, Price50 = 13, Price100 = 12, CategoryId = 9 },
                new Product { Id = 80, Title = "Apple HomePod Mini", Description = "Smart speaker with Siri", Quantity = 70, Brand = "Apple", ListPrice = 120, Price = 115, Price50 = 110, Price100 = 105, CategoryId = 27 },
                new Product { Id = 81, Title = "Sony PS5 Game - FIFA 24", Description = "Latest football game for PS5", Quantity = 150, Brand = "Sony", ListPrice = 70, Price = 65, Price50 = 62, Price100 = 60, CategoryId = 30 },
                new Product { Id = 82, Title = "Nike Backpack", Description = "Durable everyday backpack", Quantity = 90, Brand = "Nike", ListPrice = 65, Price = 60, Price50 = 58, Price100 = 55, CategoryId = 8 },
                new Product { Id = 83, Title = "Samsung Galaxy A54", Description = "Affordable Android smartphone", Quantity = 100, Brand = "Samsung", ListPrice = 350, Price = 330, Price50 = 320, Price100 = 310, CategoryId = 21 },
                new Product { Id = 84, Title = "Adidas Training Gloves", Description = "Fitness gloves for gym training", Quantity = 100, Brand = "Adidas", ListPrice = 25, Price = 23, Price50 = 22, Price100 = 20, CategoryId = 77 },
                new Product { Id = 85, Title = "Sony PlayStation Camera", Description = "HD camera for streaming", Quantity = 55, Brand = "Sony", ListPrice = 70, Price = 65, Price50 = 62, Price100 = 60, CategoryId = 30 },
                new Product { Id = 86, Title = "Gucci Earrings", Description = "Luxury fashion earrings", Quantity = 40, Brand = "Gucci", ListPrice = 500, Price = 480, Price50 = 470, Price100 = 460, CategoryId = 10 },
                new Product { Id = 87, Title = "Samsung Galaxy Tab A7", Description = "Affordable Android tablet", Quantity = 80, Brand = "Samsung", ListPrice = 250, Price = 240, Price50 = 230, Price100 = 220, CategoryId = 22 },
                new Product { Id = 88, Title = "Nike Running Jacket", Description = "Light jacket for outdoor running", Quantity = 95, Brand = "Nike", ListPrice = 90, Price = 85, Price50 = 82, Price100 = 80, CategoryId = 1 },
                new Product { Id = 89, Title = "Apple Pencil 2", Description = "Stylus for iPad Pro", Quantity = 60, Brand = "Apple", ListPrice = 130, Price = 125, Price50 = 122, Price100 = 120, CategoryId = 22 },
                new Product { Id = 90, Title = "Sony 75 Inch 8K TV", Description = "Premium 8K HDR Smart TV", Quantity = 15, Brand = "Sony", ListPrice = 5000, Price = 4900, Price50 = 4800, Price100 = 4700, CategoryId = 31 },
                new Product { Id = 91, Title = "Levi’s Denim Shorts", Description = "Classic denim shorts for summer", Quantity = 110, Brand = "Levi’s", ListPrice = 45, Price = 42, Price50 = 40, Price100 = 38, CategoryId = 1 },
                new Product { Id = 92, Title = "Samsung Galaxy S22", Description = "High-performance Android phone", Quantity = 70, Brand = "Samsung", ListPrice = 700, Price = 680, Price50 = 660, Price100 = 640, CategoryId = 21 },
                new Product { Id = 93, Title = "Nike Gym Towel", Description = "Absorbent sports towel", Quantity = 180, Brand = "Nike", ListPrice = 18, Price = 16, Price50 = 15, Price100 = 14, CategoryId = 9 },
                new Product { Id = 94, Title = "Adidas Tracksuit", Description = "Full tracksuit for men", Quantity = 100, Brand = "Adidas", ListPrice = 95, Price = 90, Price50 = 88, Price100 = 85, CategoryId = 1 },
                new Product { Id = 95, Title = "Apple AirTag", Description = "Smart Bluetooth tracker", Quantity = 120, Brand = "Apple", ListPrice = 30, Price = 28, Price50 = 27, Price100 = 25, CategoryId = 25 },
                new Product { Id = 96, Title = "Gucci Bracelet", Description = "Luxury gold bracelet", Quantity = 30, Brand = "Gucci", ListPrice = 1200, Price = 1150, Price50 = 1120, Price100 = 1100, CategoryId = 97 },
                new Product { Id = 97, Title = "Samsung 49 Inch Curved Monitor", Description = "Ultra-wide curved gaming monitor", Quantity = 20, Brand = "Samsung", ListPrice = 1000, Price = 950, Price50 = 920, Price100 = 900, CategoryId = 23 },
                new Product { Id = 98, Title = "Nike Training Shoes Men", Description = "Lightweight training sneakers", Quantity = 140, Brand = "Nike", ListPrice = 85, Price = 80, Price50 = 78, Price100 = 75, CategoryId = 4 },
                new Product { Id = 99, Title = "Sony PS5 Game - God of War", Description = "Action-adventure exclusive game", Quantity = 80, Brand = "Sony", ListPrice = 70, Price = 65, Price50 = 62, Price100 = 60, CategoryId = 30 },
                new Product { Id = 100, Title = "Apple AirPods Max", Description = "High-end over-ear headphones", Quantity = 40, Brand = "Apple", ListPrice = 600, Price = 580, Price50 = 560, Price100 = 540, CategoryId = 26 }
            );

            modelBuilder.Entity<Product>().HasData(
                new Product { Id = 101, Title = "Nike Running Shorts", Description = "Lightweight breathable shorts for running", Quantity = 120, Brand = "Nike", ListPrice = 35, Price = 32, Price50 = 30, Price100 = 28, CategoryId = 1 },
                new Product { Id = 102, Title = "Apple Watch Series 8", Description = "Smartwatch with health tracking features", Quantity = 60, Brand = "Apple", ListPrice = 450, Price = 440, Price50 = 430, Price100 = 420, CategoryId = 24 },
                new Product { Id = 103, Title = "Samsung Galaxy Note 20", Description = "High-performance smartphone with S Pen", Quantity = 50, Brand = "Samsung", ListPrice = 950, Price = 920, Price50 = 900, Price100 = 880, CategoryId = 21 },
                new Product { Id = 104, Title = "Sony Noise Cancelling Headphones", Description = "Over-ear headphones with premium sound", Quantity = 70, Brand = "Sony", ListPrice = 350, Price = 340, Price50 = 330, Price100 = 320, CategoryId = 26 },
                new Product { Id = 105, Title = "Adidas Football", Description = "Official size 5 match football", Quantity = 140, Brand = "Adidas", ListPrice = 40, Price = 38, Price50 = 36, Price100 = 34, CategoryId = 77 },
                new Product { Id = 106, Title = "Nike Yoga Mat", Description = "Durable non-slip yoga mat", Quantity = 100, Brand = "Nike", ListPrice = 55, Price = 52, Price50 = 50, Price100 = 48, CategoryId = 77 },
                new Product { Id = 107, Title = "Apple MacBook Pro", Description = "Professional laptop with M2 chip", Quantity = 30, Brand = "Apple", ListPrice = 1600, Price = 1580, Price50 = 1550, Price100 = 1520, CategoryId = 23 },
                new Product { Id = 108, Title = "Gucci Handbag", Description = "Luxury leather handbag for women", Quantity = 25, Brand = "Gucci", ListPrice = 2200, Price = 2150, Price50 = 2100, Price100 = 2050, CategoryId = 7 },
                new Product { Id = 109, Title = "Samsung Galaxy Watch 5", Description = "Smartwatch with fitness tracking", Quantity = 80, Brand = "Samsung", ListPrice = 350, Price = 340, Price50 = 330, Price100 = 320, CategoryId = 24 },
                new Product { Id = 110, Title = "Sony PlayStation 5 Console", Description = "Next-gen gaming console", Quantity = 35, Brand = "Sony", ListPrice = 600, Price = 580, Price50 = 570, Price100 = 560, CategoryId = 29 },
                new Product { Id = 111, Title = "Adidas Training Shoes Women", Description = "Comfortable sneakers for training", Quantity = 90, Brand = "Adidas", ListPrice = 70, Price = 65, Price50 = 62, Price100 = 60, CategoryId = 5 },
                new Product { Id = 112, Title = "Apple Lightning Cable", Description = "Charging cable for iPhone and iPad", Quantity = 200, Brand = "Apple", ListPrice = 20, Price = 18, Price50 = 17, Price100 = 16, CategoryId = 21 },
                new Product { Id = 113, Title = "Nike Windbreaker Jacket", Description = "Lightweight jacket for windy weather", Quantity = 70, Brand = "Nike", ListPrice = 80, Price = 75, Price50 = 72, Price100 = 70, CategoryId = 1 },
                new Product { Id = 114, Title = "Samsung Soundbar", Description = "High-quality sound system", Quantity = 45, Brand = "Samsung", ListPrice = 400, Price = 380, Price50 = 370, Price100 = 360, CategoryId = 27 },
                new Product { Id = 115, Title = "Sony PlayStation DualSense Controller", Description = "Wireless controller for PS5", Quantity = 120, Brand = "Sony", ListPrice = 70, Price = 65, Price50 = 62, Price100 = 60, CategoryId = 29 },
                new Product { Id = 116, Title = "Gucci Sunglasses", Description = "Designer sunglasses with UV protection", Quantity = 35, Brand = "Gucci", ListPrice = 700, Price = 680, Price50 = 660, Price100 = 640, CategoryId = 12 },
                new Product { Id = 117, Title = "Apple iPad Mini", Description = "Compact tablet for daily use", Quantity = 55, Brand = "Apple", ListPrice = 500, Price = 490, Price50 = 480, Price100 = 470, CategoryId = 22 },
                new Product { Id = 118, Title = "Adidas Sports Cap", Description = "Adjustable cap for sports", Quantity = 150, Brand = "Adidas", ListPrice = 25, Price = 23, Price50 = 22, Price100 = 20, CategoryId = 9 },
                new Product { Id = 119, Title = "Samsung QLED 65 Inch TV", Description = "Smart QLED 4K TV", Quantity = 25, Brand = "Samsung", ListPrice = 1400, Price = 1370, Price50 = 1350, Price100 = 1320, CategoryId = 31 },
                new Product { Id = 120, Title = "Nike Kids Sneakers", Description = "Comfortable sneakers for children", Quantity = 110, Brand = "Nike", ListPrice = 50, Price = 48, Price50 = 46, Price100 = 44, CategoryId = 6 },
                new Product { Id = 121, Title = "Sony Bluetooth Speaker", Description = "Portable wireless speaker", Quantity = 90, Brand = "Sony", ListPrice = 120, Price = 115, Price50 = 110, Price100 = 105, CategoryId = 27 },
                new Product { Id = 122, Title = "Apple Mac Mini", Description = "Compact desktop computer", Quantity = 40, Brand = "Apple", ListPrice = 800, Price = 780, Price50 = 760, Price100 = 740, CategoryId = 23 },
                new Product { Id = 123, Title = "Gucci Wallet", Description = "Luxury leather wallet for men", Quantity = 40, Brand = "Gucci", ListPrice = 500, Price = 480, Price50 = 470, Price100 = 460, CategoryId = 10 },
                new Product { Id = 124, Title = "Samsung Galaxy Tab S8", Description = "High-performance Android tablet", Quantity = 70, Brand = "Samsung", ListPrice = 700, Price = 680, Price50 = 660, Price100 = 640, CategoryId = 22 },
                new Product { Id = 125, Title = "Nike Training Gloves", Description = "Durable fitness gloves", Quantity = 95, Brand = "Nike", ListPrice = 30, Price = 28, Price50 = 27, Price100 = 25, CategoryId = 77 },
                new Product { Id = 126, Title = "Sony PS5 Game - Horizon", Description = "Open world adventure game", Quantity = 85, Brand = "Sony", ListPrice = 70, Price = 65, Price50 = 62, Price100 = 60, CategoryId = 30 },
                new Product { Id = 127, Title = "Apple AirPods Pro 2", Description = "Wireless earbuds with noise cancellation", Quantity = 80, Brand = "Apple", ListPrice = 250, Price = 240, Price50 = 230, Price100 = 220, CategoryId = 26 },
                new Product { Id = 128, Title = "Adidas Training Pants Men", Description = "Comfortable track pants", Quantity = 100, Brand = "Adidas", ListPrice = 60, Price = 55, Price50 = 53, Price100 = 50, CategoryId = 1 },
                new Product { Id = 129, Title = "Samsung Galaxy M33", Description = "Mid-range Android smartphone", Quantity = 95, Brand = "Samsung", ListPrice = 280, Price = 270, Price50 = 260, Price100 = 250, CategoryId = 21 },
                new Product { Id = 130, Title = "Nike Training Bag Medium", Description = "Duffel bag for gym and sports", Quantity = 70, Brand = "Nike", ListPrice = 65, Price = 62, Price50 = 60, Price100 = 58, CategoryId = 7 },
                new Product { Id = 131, Title = "Sony PS5 VR2 Headset", Description = "Virtual reality headset for PlayStation 5", Quantity = 40, Brand = "Sony", ListPrice = 550, Price = 540, Price50 = 530, Price100 = 520, CategoryId = 29 },
                new Product { Id = 132, Title = "Apple iMac 24 Inch", Description = "All-in-one desktop computer", Quantity = 30, Brand = "Apple", ListPrice = 1500, Price = 1470, Price50 = 1450, Price100 = 1420, CategoryId = 23 },
                new Product { Id = 133, Title = "Gucci Belt", Description = "Designer leather belt", Quantity = 50, Brand = "Gucci", ListPrice = 600, Price = 580, Price50 = 560, Price100 = 540, CategoryId = 10 },
                new Product { Id = 134, Title = "Samsung Galaxy Buds Pro", Description = "Premium wireless earbuds", Quantity = 90, Brand = "Samsung", ListPrice = 220, Price = 210, Price50 = 205, Price100 = 200, CategoryId = 26 },
                new Product { Id = 135, Title = "Nike Hoodie Women", Description = "Stylish hoodie for women", Quantity = 85, Brand = "Nike", ListPrice = 55, Price = 52, Price50 = 50, Price100 = 48, CategoryId = 2 },
                new Product { Id = 136, Title = "Sony 85 Inch 4K TV", Description = "Large screen smart TV", Quantity = 20, Brand = "Sony", ListPrice = 2500, Price = 2450, Price50 = 2400, Price100 = 2350, CategoryId = 31 },
                new Product { Id = 137, Title = "Apple iPhone 14", Description = "Latest iPhone with advanced features", Quantity = 60, Brand = "Apple", ListPrice = 1100, Price = 1080, Price50 = 1060, Price100 = 1040, CategoryId = 21 },
                new Product { Id = 138, Title = "Adidas Training Shoes Kids", Description = "Lightweight sneakers for kids", Quantity = 100, Brand = "Adidas", ListPrice = 45, Price = 42, Price50 = 40, Price100 = 38, CategoryId = 6 },
                new Product { Id = 139, Title = "Samsung Galaxy S21 Ultra", Description = "Flagship Android smartphone", Quantity = 40, Brand = "Samsung", ListPrice = 1200, Price = 1180, Price50 = 1160, Price100 = 1140, CategoryId = 21 },
                new Product { Id = 140, Title = "Nike Training Socks Pack", Description = "Pack of 3 cotton socks", Quantity = 200, Brand = "Nike", ListPrice = 20, Price = 18, Price50 = 17, Price100 = 16, CategoryId = 9 },
                new Product { Id = 141, Title = "Sony PS5 Game - Gran Turismo", Description = "Racing game for PS5", Quantity = 100, Brand = "Sony", ListPrice = 70, Price = 65, Price50 = 62, Price100 = 60, CategoryId = 30 },
                new Product { Id = 142, Title = "Apple AirPods Case", Description = "Protective silicone case", Quantity = 150, Brand = "Apple", ListPrice = 15, Price = 14, Price50 = 13, Price100 = 12, CategoryId = 26 },
                new Product { Id = 143, Title = "Gucci Necklace", Description = "Luxury gold necklace", Quantity = 25, Brand = "Gucci", ListPrice = 1500, Price = 1480, Price50 = 1460, Price100 = 1440, CategoryId = 97 },
                new Product { Id = 144, Title = "Samsung Galaxy Watch 4", Description = "Smartwatch with fitness features", Quantity = 65, Brand = "Samsung", ListPrice = 300, Price = 290, Price50 = 280, Price100 = 270, CategoryId = 24 },
                new Product { Id = 145, Title = "Nike Sports Bottle", Description = "Reusable water bottle", Quantity = 180, Brand = "Nike", ListPrice = 18, Price = 16, Price50 = 15, Price100 = 14, CategoryId = 77 },
                new Product { Id = 146, Title = "Adidas Hoodie Men", Description = "Casual hoodie for daily wear", Quantity = 80, Brand = "Adidas", ListPrice = 60, Price = 55, Price50 = 52, Price100 = 50, CategoryId = 1 },
                new Product { Id = 147, Title = "Sony Home Theater System", Description = "Premium surround sound system", Quantity = 30, Brand = "Sony", ListPrice = 1200, Price = 1180, Price50 = 1160, Price100 = 1140, CategoryId = 27 },
                new Product { Id = 148, Title = "Apple iPhone Case", Description = "Protective case for iPhone models", Quantity = 200, Brand = "Apple", ListPrice = 25, Price = 23, Price50 = 22, Price100 = 20, CategoryId = 21 },
                new Product { Id = 149, Title = "Nike Sweatpants Men", Description = "Comfortable sweatpants", Quantity = 100, Brand = "Nike", ListPrice = 50, Price = 48, Price50 = 46, Price100 = 44, CategoryId = 1 },
                new Product { Id = 150, Title = "Samsung Galaxy S10", Description = "Reliable Android smartphone", Quantity = 75, Brand = "Samsung", ListPrice = 500, Price = 480, Price50 = 460, Price100 = 440, CategoryId = 21 }
            );



        }
    }

}
